### PR TITLE
Add SEXP cast operator for roptional

### PR DESCRIPTION
**Pull request by SylvainCorlay**
cc @DavisVaughan .

### CODE REVIEW

**Comment by DavisVaughan** [comment]
Oh wait does this have something to do with the Exporter that uses the now-renamed roptional_assembly https://github.com/QuantStack/xtensor-r/blob/master/include/xtensor-r/rcpp_extensions.hpp

**Comment by DavisVaughan** [comment]
Is it smart to also define wrap() methods for the rarray_optional and rtensor_optional types like how is done at the very bottom of rarray https://github.com/QuantStack/xtensor-r/blob/master/include/xtensor-r/rarray.hpp

I think (?) this gets us the automatic conversation from rarray_optional to SEXP which I would use a lot

**Comment by DavisVaughan** [comment]
In this PR the SEXP() operators were changed out for a different mechanism (relying on Rcpp storage policies maybe?). I don't actually know how SEXP() is currently working on rarray but we may want to implement this in the same way https://github.com/QuantStack/xtensor-r/pull/68

**Comment by SylvainCorlay** [comment]
> In this PR the SEXP() operators were changed out for a different mechanism (relying on Rcpp storage policies maybe?). I don't actually know how SEXP() is currently working on rarray but we may want to implement this in the same way #68

I think that you are right. This should be done with the wrap method indeed.

I need to go give a class. Do you want to open the PR with that version? Closing this PR.

**Comment by DavisVaughan** [comment]
I'll give it a shot

**Comment by SylvainCorlay** [comment]
This is a good occasion to make the exporters for `roptional_array` and `roptional_tensor`.

**Pull request closed without merging**
