### PR TITLE
include xtensor headers in package

### PR DESCRIPTION
**Pull request by eddelbuettel**
taken from xtensor repo at release 0.10.3 and commit 504da95

including headers has the advantage of 
  - making the package self-sufficient, ie can now build on Travis
  - able to provide headers for other packages, see eg [BH](https://cran.r-project.org/package=BH), [AsioHeaders](https://cran.r-project.org/package=AsioHeaders) and more

possible downside of a diff to xtensor itself easy to manage to same team behind both

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks @eddelbuettel for looking at this.

I am not comfortable vendoring xtensor headers as part of this repo with `xtensor-r`. Our strategy so far has been to split things in atomic packages with a clear separation of concerns (`xtensor-blas`, `xtensor-julia`, `xtensor-python`, `xtensor-r`, and soon `xtensor-arrow` and `xtensor-fftw`...) and shipping packages for package managers like dpkg and conda. Besides, xtensor will soon have a dependency on `xsimd` etc...

I don't know R packaging. Is there a general "unix-style installation prefix" where CRAN packages install packages? Could we imagine performing the bundling of xtensor headers as part of the build process for a CRAN package?

**Comment by SylvainCorlay** [comment]
We could have a dummy `xtensor-core` CRAN package that vendors the xtensor core headers?

We are considering a similar solution for Julia (METADATA.jl) and python (pypi) distribution, while the debian package for xtensor-julia and xtensor-python would simply depend on the regular xtensor package.

**Comment by eddelbuettel** [comment]
> We could have a dummy xtensor-core CRAN package

Yes of course. That is the very idea I started from when thought about this morning when commuting in.  And the existing CRAN packages BH, AsioHeaders, StanHeaders, ... are similar.   But think through where we are _right now_:   xtensor-r *is* that dummy package.   By having it, other can / could depend on it.  And having minimal example code along with headers is no detriment, see RcppArmadillo and RcppEigen.

Moreover by having the headers in there _right now_ we could now turn on Travis right now and make the test development better.

This is all still super-exploratory and not yet meant for CRAN.    To be refined before it gets submitted.

And there is more to discuss (entire CRAN Policy, and "the way things are done") which I am happy to help with but don't have time for right now.

Lastly, I love planning these things through for Debian too.  But Debian users may be 2% or less of all CRAN users.  What the PR does is offer xtensor from R to every R user.

**Comment by SylvainCorlay** [comment]
Regarding CI, we can certainly enable Travis and Appveyor without vendoring the headers by installing xtensor manually as part of the build process.

**Comment by eddelbuettel** [comment]
And:

> I don't know R packaging. Is there a general "unix-style installation prefix" where CRAN packages install packages?

Yes, `inst/include/${packageName}`.  Then _any_ other CRAN package declares `LinkingTo: ${packageName}` and gets a `-I....` path delivers from R.  *Cross-platform*.  Absolutely awesome for header-only package such as this.

See eg [this line of my (simple) anytime package](https://github.com/eddelbuettel/anytime/blob/master/DESCRIPTION#L17) giving it Rcpp headers, Boost headers (and an exported R API utility package, ignore that).  I can show you hundreds of examples.

**Comment by eddelbuettel** [comment]
> Regarding CI, we can certainly enable Travis and Appveyor without vendoring the headers by installing xtensor manually as part of the build process.

I am happy to leave you guys alone.  I was just trying to show you how to the package built NOW on Windows, macOS, and Linux.  Without requiring anything extra -- but all means please close if it is a distraction to you.

**Comment by SylvainCorlay** [comment]
> > I don't know R packaging. Is there a general "unix-style installation prefix" where CRAN packages install packages?

> Yes, 

This is great news compared to Julia, where each package has its prefix and requires using `-D foobar_DIR=...` for each dependency...

**Comment by eddelbuettel** [comment]
> This is great news compared to Julia, where each package has its prefix and requires using -D foobar_DIR=... for each dependency...

Yes, `R CMD INSTALL ...` does that dynamically when the client package it built.  (Also see my edited previous comment which I expanded slightly.)

**Comment by SylvainCorlay** [comment]
> I am happy to leave you guys alone. I was just trying to show you how to the package built NOW on Windows, macOS, and Linux. Without requiring anything extra -- but all means please close if it is a distraction to you.

Please don't! We have little experience with R packaging and Rcpp. I am just not comfortable with duplicating all of xtensor into this repo.

From what you said earlier, we can probably do

```
    - git clone https://github.com/QuantStack/xtensor
    - cd xtensor
    - cmake -DCMAKE_INSTALL_PREFIX=R_INSTALLATION_PREFIX .
    - make install
```

as part of the travis.yml. See e.g. https://github.com/QuantStack/xtensor-blas/blob/0.1.0/.travis.yml#L109

**Comment by eddelbuettel** [comment]
Is there a phone I can reach you at?  DM me on twitter, maybe?

(There is too much context.  With 20+ years with Debian I *love* have system-wide packages.  But for R I also need to think about the poor lost souls on Windows, macOS,  RHEL, .... so it also beneficial to use the _language_ packaging mechanism.  Because the one for R is actually really good.   Hence header packages.  I still say merge this to get feet wet, this is not necessarily going to be our first CRAN package.)

**Comment by SylvainCorlay** [comment]
Do you want to hop on appear.in/xtensor ?

**Comment by SylvainCorlay** [comment]
After some in-person discussions with Dirk, Wolf and Johan, here is a proposal:

- we would like to not vendor `xtensor` headers in this repository.
-  the CRAN package tarball would not reflect the content of this repository. Instead, we would generate its content by performing a `cmake -D CMAKE_INSTALL_PREFIX=PKG_ROOT` and `make install` for both `xtensor` and `xtensor-r`.
- eventually, the directory structure of the CRAN tarball would be

```
inst/include/xtensor/[xtensor headers]
inst/share/cmake/xtensor/xtensorConfig.cmake
inst/share/cmake/xtensor/xtensorConfigVersion.cmake
inst/include/xtensor-r/[xtensor-r headers]
inst/share/cmake/xtensor-r/xtensor-rConfig.cmake
inst/share/cmake/xtensor-r/xtensor-rConfigVersion.cmake
```

i.e. vendoring `xtensor` in the CRAN package and not in the repo.

 - Eventually, the directory structure of the `xtensor-r` repository will be that of a regular C++ package (see e.g. `xtensor`, `xeus`, `xsimd`), containing a CMakeLists.txt at the root level.
 - unlike RCpp armadillo, we would not provide a header including everything at the root of `inst/include/`

**Comment by eddelbuettel** [comment]
Hm.  Not sure about this but about to commute to work.

**Comment by eddelbuettel** [comment]
There are now two working, minimal repos complete with Travis CI testing you can use as a stanza (or ignore as you wish):  
- [xtensorHeaders](https://github.com/eddelbuettel/xtensorHeaders) is basically "just you", I combined xtensor and (what was then current of) xtensor-r into one header-only package called 'xtensor' (within the R packages namespace). You could split it into two if you prefer.  At this level we have almost no R.
- [xtensorExamples](https://github.com/eddelbuettel/xtensorExamples) is a minimal client package, dependending on 'xtensor'.
Again, it is just meant as a suggestion.  This is how I would lay it out for use by R.

Now, I understand where you come from and how you want consistent testing across OSs and client languages for xtensor.  That's _hard_.  I just wanted to show here how a _minimal_ R solution could look like.

**Comment by eddelbuettel** [comment]
Oh, and of course they pass `R CMD check --as-cran` under the r-devel version -- my packaging standard.

**Comment by SylvainCorlay** [comment]
@eddelbuettel thanks for iterating on this. 

1) Regarding the tests, all our language bindings have two test suites

 - A test suite ran by the target language (`pytest` for python, `Pkg.test` for Julia)
 - A test suite ran by C++, which embeds the target interpreter and does the instantiations from C++.

We were generally able to catch a lot more issues with the second form, by testing the value semantics etc... without writing too much binding code.

2) Regarding the `tar.gz` for CRAN, the approach that we are considering is to generate its content including the vendoring of xtensor and other dependencies with our CI and upload it upon release to the GH release files using e.g. https://docs.travis-ci.com/user/deployment/releases/

**Comment by eddelbuettel** [comment]
Thanks for elaborating.   You are of course entirely free to do whatever you choose, and deploy whichever tools you deem suitable.  It is your project after all.

But if you want R users to look at it and possibly even use it, I would recommend trying a little harder to look and feel like a unit understood by R users: an R package.   

So if I were you, I'd hide non-standard front-ends like `install_and_test.R`.  But that's just me, so feel free to apply whichever (steep!) discount factor to whatever I say ...

**Comment by SylvainCorlay** [comment]
The install_and_test thing is is a place holder. Wolf put all of this together over the week end. Please bare with us as we are on the very early stages.

**Comment by eddelbuettel** [comment]
Well I offered a perfectly compliant stanza so by all means copy along.

I remain happy to help.  This is cool stuff so we should get it integrated.

**Comment by SylvainCorlay** [comment]
@eddelbuettel By the way, we now have a cmake target that builds the CRAN tarball.

```sh
cmake  .
make cran
```

The generated `tar.gz` package still has a couple of warnings when doing `R CMD check --as-cran xtensor_0.1.0-0.tar.gz`, namely:

```
* checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'rcpp_hello_xtensor':
rcpp_hello_xtensor
  Code: function(tens)
  Docs: function()
  Argument names in code not in docs:
    tens
```

and

```
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
```

**Pull request closed without merging**
