### PR TITLE
Split xtensor-r and Xtensor.R

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@wolfv I leave it to you to merge this!

**Comment by wolfv** [comment]
Looks good to me!

Is there no way to run the R-only unit test on commit in this repo?

**Comment by SylvainCorlay** [comment]
> Is there no way to run the R-only unit test on commit in this repo?

Not at the moment.

We could install `Xtensor.R` with `--configure-args=`--novendor` as part of this and check that we can build the same unit test.

**Comment by wolfv** [comment]
I think that would be cool so that we keep the unit tests on push in here

do you want to merge now or should we figure that out first?

**Comment by SylvainCorlay** [comment]
Working on the build for Xtensor.R in a separate PR

**Pull request merged**
